services:
  web:
    image: __IMAGE__    # será reemplazado por el pipeline
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: